---
title: "CytB Tree Plot"
author: "Jon Nations"
date: "`r Sys.Date()`"
output: html_document
---

# Plotting the Concatenated trees for the sumatra description

I'm using the same format as the cytb tree

## Load Data and Packages

```{r}
pacman::p_load(treedataverse, tidyverse, ape, TDbook, ggbreak, patchwork, ggpubr)

```

```{r}
#con <- read.nexus('trees/concat.nex.contre')

con2 <- treeio::read.iqtree('trees/partition_no_lasi.nex.contree')

#cytb2 <- root(cytb2, outgroup = "Suncus_murinus_AB033610.1", edgelabel = T, resolve.root = T)
node<-which(con2@phylo$tip.label=="Crocidura_monax__Tanzania__FMNH173776")
position<-0.5*con2@phylo$edge.length[which(con2@phylo$edge[,2]== node)]
con2@phylo <- phytools::reroot(con2@phylo, node, position)
```

Quick Plot works! Always a plus.

```{r}
#ggtree(con2) + geom_tiplab()
```

############# 

Stopped here \############### Alright, things to do - Fix names

```{r}
#newname <- gsub("__\\A-Za-z\\__", " (\\A-Za-z\\) ", cytb$tip.label)
tt <- con2@phylo$tip.label 
tt2 <- str_split_fixed(tt, "_", 6)
tt2 <- as.data.frame(tt2) %>% select(!c('V3', 'V5'))
tt2 <- tidyr::unite(tt2, 'C1', V1:V2, sep = " ")
tt2 <- tidyr::unite(tt2, 'C1', c("C1", "V4"), sep = " (")
newnames <- tidyr::unite(tt2, "tip.label", c("C1", "V6"), sep = ") ") 
#newnames <- newnames %>% mutate_all( ~ str_replace_all(., "_", " "))
con2@phylo$tip.label <- as.character(newnames$tip.label)
```

```{r}
p <- ggtree(con2, ladderize=T)
p2 <- p + geom_tiplab(offset = 0.001, size = 2.8) + 
  #geom_treescale(x = 0.01, y = 0, width=0.001, offset = 0.2, fontsize = 3) +
    #scale_size_continuous(range = c(3, 10)) 
  xlim(0, 0.05)

p3 <- p2 #+ scale_x_break(c(0.04, 0.17)) + hexpand(1) 
p3
```

```{r}
p4 <- ggtree::flip(p3, getMRCA(con2@phylo, c("Crocidura umbra (Java-Gede) FMNH212780", "Crocidura monticola (Java-Ijen) LSUMZ37983" )), getMRCA(con2@phylo, c("Crocidura dewi (Sumatra-Singgalang) LSUMZ40245", "Crocidura balingka (Sumatra-Singgalang) FMNH212952")))

p4
```

## ALigned TIp Labels

```{r}
p <- ggtree(con2, ladderize=T)
pa <-p + geom_tiplab(align = F, size = 2.8) + 
  #geom_treescale(x = 0.01, y = 0, width=0.001, offset = 0.2, fontsize = 3) +
    #scale_size_continuous(range = c(3, 10)) 
  xlim(0, 0.05) 

pa <- ggtree::flip(pa, getMRCA(con2@phylo, c("Crocidura umbra (Java-Gede) FMNH212780", "Crocidura monticola (Java-Ijen) LSUMZ37983" )), getMRCA(con2@phylo, c("Crocidura dewi (Sumatra-Singgalang) LSUMZ40245", "Crocidura balingka (Sumatra-Singgalang) FMNH212952")))

pa
```


```{r}
#p <- ggtree(con2, ladderize=T)
pa2 <- pa   
  #geom_treescale(x = 0.01, y = 0, width=0.001, offset = 0.2, fontsize = 3) +
    #scale_size_continuous(range = c(3, 10)) 
#  xlim(0, 0.05) 

#pa2 <- ggtree::flip(pa, getMRCA(con2@phylo, c("Crocidura umbra (Java-Gede) FMNH212780", "Crocidura fuliginosa (Cambodia) FMNH168656")), getMRCA(con2@phylo, c("Crocidura paradoxura (Sumatra-Tujuh) FMNH212885", "Crocidura foetida (Borneo-Sarawak) USNM590299"))) 

#pa2
```


```{r}
hili <- function(node) {
  geom_hilight(
      node={{node}}, 
      alpha = 0.4,
      extend=0.02,
      type = 'roundrect',
      color=NA,
      fill="#7AD151")
}

# Get List of nodes
getMRCA(con2@phylo, c("Crocidura barapi (Sumatra-Talamau) LSUMZ39759", "Crocidura barapi (Sumatra-Talamau) LSUMZ39748"))
getMRCA(con2@phylo, c("Crocidura dewi (Sumatra-Singgalang) LSUMZ40245", "Crocidura balingka (Sumatra-Singgalang) LSUMZ40234" ))
getMRCA(con2@phylo, c("Crocidura neglecta (Sumatra-Singgalang) LSUMZ40218" , "Crocidura neglecta (Sumatra-Talamau) LSUMZ39811"  ))
getMRCA(con2@phylo, c("Crocidura neglecta (Sumatra-Tujuh) FMNH212877" , "Crocidura neglecta (Sumatra-Tujuh) FMNH212878"))
getMRCA(con2@phylo, c("Crocidura paradoxura (Sumatra-Tujuh) FMNH212885", "Crocidura paradoxura (Sumatra-Singgalang) FMNH212956"))
getMRCA(con2@phylo, c("Crocidura hutanis (Sumatra-Singgalang) FMNH212950" , "Crocidura vosmaeri (Sumatra-Bangka) LSUMZ38076"))
```

```{r}
pa3 <- pa2 + hili(146) + hili(132) + hili(126) + hili(124) + hili(110) + hili(96)
pa3
ggsave("trees/Concat_tree_1.pdf", width = 8, height = 10.5)
```

##Shrink and collapse Some Clades


```{r}
getMRCA(con2@phylo, c("Crocidura ninoyi (Philippines-Sibuyan) FMNH145686" , "Crocidura beatus (Philippines) FMNH146965"  ))

getMRCA(con2@phylo, c("Crocidura paradoxura (Sumatra-Tujuh) FMNH212885" , "Crocidura paradoxura (Sumatra-Singgalang) FMNH212956"  ))

getMRCA(con2@phylo, c("Crocidura brunnea (Java-Ciremai) MZB28409" , "Crocidura brunnea (Java-Ijen) LSUMZ37945"  ))

getMRCA(con2@phylo, c("Crocidura fuliginosa (Malaysia-Peninsula) MZB16773" , "Crocidura fuliginosa (Cambodia) FMNH168656"  ))

getMRCA(con2@phylo, c("Crocidura maxi (Java-Ijen) LSUMZ37971" , "Crocidura maxi (Aru) WAM38557"  ))

getMRCA(con2@phylo, c("Crocidura orientalis (Java-Ciremai) MZB28378" , "Crocidura orientalis (Java-Gede) FMNH212778"  ))

getMRCA(con2@phylo, c("Crocidura foetida (Borneo-Sarawak) USNM590298" , "Crocidura foetida (Borneo-Sarawak) USNM590299"  ))

getMRCA(con2@phylo, c("Crocidura monticola (Java-Slamet) LSUMZ37984" , "Crocidura monticola (Java-Slamet) LSUMZ37990"  ))

getMRCA(con2@phylo, c("Crocidura umbra (Java-Gede) FMNH212779" , "Crocidura umbra (Java-Gede) FMNH212780"  ))

getMRCA(con2@phylo, c("Crocidura monticola (Java-Gede) MZB33645" , "Crocidura monticola (Java-Salak) MZB31720"  ))

getMRCA(con2@phylo, c("Crocidura tanakae (Taiwan) NTU970" , "Crocidura tanakae (Taiwan) NTU971"  ))

getMRCA(con2@phylo, c("Crocidura elongata (Sulawesi) LSUMZ36906" , "Crocidura elongata (Sulawesi) LSUMZ36907"  ))

getMRCA(con2@phylo, c("Crocidura kurodai (Taiwan) NTU980" , "Crocidura kurodai (Taiwan) NTU981"  ))
```

Shrink and collapse Philippines Have to make the clade shapes AFTER shrinking the node

```{r} 
claps1 <- scaleClade(pa2,    85, 0.18) 
claps1 <- scaleClade(claps1, 110,  0.18) 
claps1 <- scaleClade(claps1,  90, 0.18) 
claps1 <- scaleClade(claps1, 128, 0.18) 
claps1 <- scaleClade(claps1, 149, 0.18)
claps1 <- scaleClade(claps1,  93, 0.18)
claps1 <- scaleClade(claps1,  95, 0.18)
claps1 <- scaleClade(claps1, 145, 0.18)
claps1 <- scaleClade(claps1, 143, 0.18)
claps1 <- scaleClade(claps1, 142, 0.18)
claps1 <- scaleClade(claps1, 120, 0.18)
claps1 <- scaleClade(claps1, 148, 0.18)
claps1 <- scaleClade(claps1, 119, 0.18)




claps2 <- ggtree::collapse(claps1, node = 85, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=85, label="Philippines (n=4)", offset = .003, fontsize = 3) 

claps3 <- collapse(claps2, node = 110, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=110, label="Crocidura paradoxura (n=5)", offset = .003, fontsize = 3) 

claps4 <- collapse(claps3, node = 90, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=90, label="Crocidura brunnea (n=5)", offset = .003, fontsize = 3) 

claps5 <- collapse(claps4, node = 128, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=128, label="Crocidura fuliginosa (n=3)", offset = .001, fontsize = 3) 

claps6 <- collapse(claps5, node = 149, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=149, label="Crocidura maxi (n=5)", offset = .004, fontsize = 3)

claps7 <- collapse(claps6, node = 93, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=93, label="Crocidura orientalis (n=4)", offset = .004, fontsize = 3)

claps8 <- collapse(claps7, node = 95, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=95, label="Crocidura foetida (n=2)", offset = .002, fontsize = 3) 

claps9 <- collapse(claps8, node = 145, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=145, label="Crocidura monticola B (n=2)", offset = .002, fontsize = 3)

claps10 <- collapse(claps9, node = 143, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=143, label="Crocidura umbra (n=3)", offset = .002, fontsize = 3) 

claps11 <- collapse(claps10, node = 142, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=142, label="Crocidura  monticola A (n=2)", offset = .002, fontsize = 3)

claps12 <- collapse(claps11, node = 120, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=120, label="Crocidura  tanakae (n=2)", offset = .002, fontsize = 3) 

claps13 <- collapse(claps12, node = 148, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=148, label="Crocidura  elongata (n=2)", offset = .002, fontsize = 3) 

claps14 <- collapse(claps13, node = 119, 'max', fill="white", color = 'black') + 
  geom_cladelab(node=119, label="Crocidura  kurodai (n=2)", offset = .002, fontsize = 3) +
  hili(146) + hili(132) + hili(126) + hili(124) + hili(110) + hili(96)


claps14
ggsave("trees/Concat_tree_2.pdf", width = 8, height = 10.5)
```


# Node support

```{r}
library(operators)
pa4 <- claps14 + 
  geom_nodelab(aes(x=branch, label=round(UFboot, 2), 
                   subset = !is.na(as.numeric(UFboot)) & 
                     as.numeric(UFboot) < 95 #&
                     #node %!in% drp
                   ),
               vjust=.9, 
               hjust = -.95, 
               size = 1.75) +
  geom_nodepoint(aes(label=UFboot, 
                     subset = UFboot > 95 #&
                     #node %!in% drp
                     ), 
                 size = 2, 
                 color ="black", 
                 alpha = 1)  #+
  #eom_nodepoint(aes(label=UFboot, 
  #                  subset = !is.na(as.numeric(UFboot)) &
  #                    as.numeric(UFboot) > 70 & 
  #                    as.numeric(UFboot) < 90 #&
  #                  #node %!in% drp
  #                  ), 
  #              size = 2, color ="grey40", 
  #              alpha = 1, 
  #              shape = 15)
#pa4 + geom_treescale(x = 0.001, y = 0, width=0.5, offset = 0.5, fontsize = 3)
pa4 + geom_treescale(width = 0.01,
                     y = 8,
                     offset = 0.5,
                     fontsize = 3)
ggsave("trees/Concat_tree_3.pdf", width = 8, height = 10.5)
```

